services:
  api:
    image: ghcr.io/maede97/rega-tracker-api:latest
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    restart: always
    networks:
      - default
      - traefik-proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik-proxy'
      - 'traefik.http.routers.rega-tracker-api.rule=Host(`rega-api.hueppis.com`)'
      - 'traefik.http.routers.rega-tracker-api.entrypoints=websecure'
      - 'traefik.http.routers.rega-tracker-api.tls=true'
      - 'traefik.http.routers.rega-tracker-api.tls.certresolver=letsencrypt'
      - 'traefik.http.services.rega-tracker-api.loadbalancer.server.port=8000'
    volumes:
      - ./flights.db:/app/flights.db
      - ./api_keys.txt:/app/api_keys.txt
    environment:
      - CORS_ORIGIN=rega.hueppis.com
  server:
    image: ghcr.io/maede97/rega-tracker-web:latest
    restart: always
    environment:
      - HOSTNAME=0.0.0.0
    networks:
      - default
      - traefik-proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik-proxy'
      - 'traefik.http.routers.rega-tracker-web.rule=Host(`rega.hueppis.com`)'
      - 'traefik.http.routers.rega-tracker-web.entrypoints=websecure'
      - 'traefik.http.routers.rega-tracker-web.tls=true'
      - 'traefik.http.routers.rega-tracker-web.tls.certresolver=letsencrypt'
      - 'traefik.http.services.rega-tracker-web.loadbalancer.server.port=3000'

  fetcher:
    image: ghcr.io/maede97/rega-tracker-api:latest
    command: ["python", "fetch_current_data.py"]
    restart: no
    volumes:
      - ./flights.db:/app/flights.db

networks:
  traefik-proxy:
    external: true
